---
kind: pipeline
type: docker
name: "default"

steps:
  ## TODO add a test step
  - name: ui-build
    image: node:17.7-buster
    commands:
      - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
      - pnpm install
      - pnpm run clean && pnpm run build

  - name: push
    image: thegeeklab/drone-docker-buildx
    privileged: true
    pull: if-not-exists
    settings:
      platforms:
        - linux/amd64
        - linux/arm64
