---
kind: pipeline
type: docker
name: "default"

steps:
  - name: lint
    image: kameshsampath/fruits-ui-base
    pull: if-not-exists
    commands:
      - pnpm install
      - pnpm lint

  - name: build
    image:  kameshsampath/fruits-ui-base
    pull: if-not-exists
    commands:
      - pnpm install
      - pnpm run clean && pnpm run build

  - name: push
    image: thegeeklab/drone-docker-buildx
    privileged: true
    pull: if-not-exists
    settings:
      platforms:
        - linux/amd64
        - linux/arm64
---
kind: pipeline
type: docker
name: build-base

steps:
  - name: push
    image: thegeeklab/drone-docker-buildx
    privileged: true
    pull: if-not-exists
    settings:
      dockerfile: Dockerfile.pnpm
      repo: kameshsampath/fruits-ui-base
      tag:
        - latest
      platforms:
        - linux/amd64
        - linux/arm64
