namespace: fruits-app

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app: fruits-app-ui
  version: v1.0

configMapGenerator:
  - name: ui-config
    literals:
      - "FRUITS_API_URI=http://fruits-api:8080/v1/api"
resources:
- deployment.yaml
- service.yaml
